version: 2
jobs:
  build:
    working_directory: ~/code/
    docker:
      - image: circleci/android:api-24
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Install Android NDK
          command: ls && cd simple-rt-android/ && echo $PWD && source ./circleCiEnvironmentSetup.sh && getAndroidNDK && cd /home/circleci/code//simple-rt-android/
      - run:
          name: Download Dependencies
          command: /home/circleci/code/gradlew androidDependencies          
      - run:
          name: Download Dependencies
          command: /home/circleci/code/simple-rt-android/gradlew build  
      
      
      
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: ./gradlew lint test
      - store_artifacts:
          path: app/build/outputs/
          destination: out
      - store_test_results:
          path: app/build/test-results
