version: 2
jobs:
  build:
    working_directory: ~/code/
    docker:
      - image: circleci/android:api-24
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "/home/circleci/code/simple-rt-android/build.gradle" }}-{{ checksum  "/home/circleci/code/simple-rt-android/app/build.gradle" }}
#      - run:
#         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this. 
#         command: sudo chmod +x ./gradlew
      - run:
          name: Install Android NDK
          command: ls && cd simple-rt-android/ && echo $PWD && source ./circleCiEnvironmentSetup.sh && getAndroidNDK && cd /home/circleci/code/simple-rt-android/
      - run:
          name: Download Dependencies
          command: cd /home/circleci/code/simple-rt-android && ./gradlew androidDependencies          
      - run:
          name: build apk
          command: cd /home/circleci/code/simple-rt-android && ./gradlew build  
      - run:
          name: Download c Dependencies
          command: sudo apt-get update && sudo apt-get -y install build-essential pkg-config libusb-1.0-0-dev zip
      - run:
          name: build simple-rt-cli
          command: |
            cd /home/circleci/code/simple-rt-cli/
            make
            zip -r simple-rt_linux.zip iface_up.sh simple-rt build
            mv simple-rt_linux.zip /home/circleci/code/simple-rt-android/app/build/outputs/
            

      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "/home/circleci/code/simple-rt-android/build.gradle" }}-{{ checksum  "/home/circleci/code/simple-rt-android/app/build.gradle" }}
     
      - store_artifacts:
          path: /home/circleci/code/simple-rt-android/app/build/outputs/
          destination: out
      
